#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-droolsjbpm-build-bootstrap
Version  : 6.3.0.final
Release  : 1
URL      : https://github.com/kiegroup/droolsjbpm-build-bootstrap/archive/6.3.0.Final.tar.gz
Source0  : https://github.com/kiegroup/droolsjbpm-build-bootstrap/archive/6.3.0.Final.tar.gz
Source1  : https://repo1.maven.org/maven2/org/optaplanner/optaplanner-bom/6.3.0.Final/optaplanner-bom-6.3.0.Final.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-droolsjbpm-build-bootstrap-data = %{version}-%{release}
Requires: mvn-droolsjbpm-build-bootstrap-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
Developing Drools and jBPM
==========================
**If you want to build or contribute to a droolsjbpm project, read this document.**

%package data
Summary: data components for the mvn-droolsjbpm-build-bootstrap package.
Group: Data

%description data
data components for the mvn-droolsjbpm-build-bootstrap package.


%package license
Summary: license components for the mvn-droolsjbpm-build-bootstrap package.
Group: Default

%description license
license components for the mvn-droolsjbpm-build-bootstrap package.


%prep
%setup -q -n droolsjbpm-build-bootstrap-6.3.0.Final

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-droolsjbpm-build-bootstrap
cp LICENSE-ASL-2.0.txt %{buildroot}/usr/share/package-licenses/mvn-droolsjbpm-build-bootstrap/LICENSE-ASL-2.0.txt
cp ide-configuration/LICENSE-ASL-2.0-HEADER.txt %{buildroot}/usr/share/package-licenses/mvn-droolsjbpm-build-bootstrap/ide-configuration_LICENSE-ASL-2.0-HEADER.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/optaplanner/optaplanner-bom/6.3.0.Final
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/optaplanner/optaplanner-bom/6.3.0.Final/optaplanner-bom-6.3.0.Final.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/optaplanner/optaplanner-bom/6.3.0.Final/optaplanner-bom-6.3.0.Final.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-droolsjbpm-build-bootstrap/LICENSE-ASL-2.0.txt
/usr/share/package-licenses/mvn-droolsjbpm-build-bootstrap/ide-configuration_LICENSE-ASL-2.0-HEADER.txt
